### ISSUE TITLE
Spike::Backend or IndexedDB

### ISSUE THREAD

**Issue by rashi-bhansali** [cse210-fa24-group14/cse210-fa24-group14#36]

**Comment by rashi-bhansali** [comment]
We don't need to worry about IndexedDB or Backend for now, since we're using chrome.storage.sync() APIs for persistent storage of notes across devices. Can look into this later, when we look to extend our extension to other browsers maybe?

**Comment by Shyam-Sundar-Bharathi** [comment]
Does this mean that mapping notes to URLs also works?
