### ISSUE TITLE
Feature-Automating-Releases-To-Deploy-Chrome-Extension

### ISSUE THREAD

**Issue by rashi-bhansali** [cse210-fa24-group14/cse210-fa24-group14#51]
| Name        | About                           | Title                  | Labels       | Assignees                        |
|-------------|---------------------------------|------------------------|--------------|----------------------------------|
| Feature     | Releasing automated deployments to Chrome Web Store | Feature-Automating-Releases-To-Deploy-Chrome-Extension | enhancement  | `Shyam-Sundar-Bharathi`, `MitchelHsu`, `rashi-bhansali`  |

**Is your feature request related to a problem? Please describe.**  
Currently, the process of deploying our Chrome extension to the Chrome Web Store (CWS) is manual (user has to manually upload the extension code .zip to Chrome Extensions > Load Unpacked in Developer Mode), which is time-consuming, error-prone and inconvenient. Automating this process through the CD pipeline will streamline deployments and ensure consistency, especially since already have the CI part setup.

**Describe the solution you'd like**  
We plan to set up a Continuous Deployment (CD) pipeline to automatically release our Chrome extension from GitHub to the Chrome Web Store. This will include:  
- Creating a developer account on CWS (with a nominal one-time fee of 5$).  
- Using the **Chrome Web Store Publish** action available on the GitHub Marketplace.  
- Configuring the existing CI/CD pipeline to authenticate with CWS and publish updates whenever changes are pushed to the **main** branch (or we can setup a release branch where changes are pushed from main branch on a weekly basis).

**Describe alternatives you've considered**  
- Using custom scripts for CWS deployment, but this would require additional maintenance and might not provide the reliability and community support of the GitHub action.  
- Keeping the deployment process manual, but this introduces inefficiencies, risks and inaccessibility.

**Additional context**  
- This feature will improve the development workflow by reducing deployment delays and errors.  
- Reference documentation: [Chrome Web Store Developer Guide](https://developer.chrome.com/docs/webstore/).

**Comment by Shyam-Sundar-Bharathi** [comment]
Waiting for CWS to approve our review request!
